/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.crio.starter;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class V1Application {

	public static void main(String[] args) {
		SpringApplication.run(V1Application.class, args);
		System.out.println("Server started!");
	}

}